### ISSUE TITLE
JSON full support?

### ISSUE THREAD

**Issue by doriandrn** [JBlaak/Fitted#29]
I've been trying to send over POST a JSON stringified object and am expecting to receive the same. Athough using a custom processor, req/res typeof is a string and methods such as 'isOk' can't be bound to it.

TypeError: Cannot create property 'method' on string

**Comment by JBlaak** [comment]
Can you maybe show me some more code how you're trying to get this up and running?

By default no `Content-Type` and `Accept` headers are set, this might already solve your problems.
